<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cantidades</name>
   <tag></tag>
   <elementGuidId>0b597522-67c9-4d27-b1aa-fbd6c81d83f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.form-control.form-control-lg.select-dropdown-button.select-dropdown-button-product-quantity.hidden-sm-down</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
