<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tallas</name>
   <tag></tag>
   <elementGuidId>80364e85-f1a0-4858-9c5e-66dc7bf4e35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.form-control.form-control-lg.select-dropdown-button.select-dropdown-button-normal-select-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
