<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Talla</name>
   <tag></tag>
   <elementGuidId>576a27a2-1f6c-4d19-979e-02062b7dc178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal-select-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${GlobalVariable.TALLA}' or . = '${GlobalVariable.TALLA}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;select-dropdown-list-normal-select-1&quot;]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>${GlobalVariable.TALLA}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal-select-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.TALLA}</value>
   </webElementProperties>
</WebElementEntity>
